// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk0j_xU34w3f1r8bnbnGboJ-szKT1C-P8',
    appId: '1:297343455729:web:5a5b7a6e5f4672d7547450',
    messagingSenderId: '297343455729',
    projectId: 'kaihi-30976',
    authDomain: 'kaihi-30976.firebaseapp.com',
    storageBucket: 'kaihi-30976.firebasestorage.app',
    measurementId: 'G-B1C6S11L72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH14sPykrugdaayWNTLdL_yf8ps6Et7eI',
    appId: '1:297343455729:android:390084048b6b2c77547450',
    messagingSenderId: '297343455729',
    projectId: 'kaihi-30976',
    storageBucket: 'kaihi-30976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATqxtYu6rgDdsAi1zbsXoKCbkc6F79wK8',
    appId: '1:297343455729:ios:0a986b2f98b4a8ac547450',
    messagingSenderId: '297343455729',
    projectId: 'kaihi-30976',
    storageBucket: 'kaihi-30976.firebasestorage.app',
    iosBundleId: 'com.example.kaihi',
  );
}
